// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalUltra.Infrastructure;

#nullable disable

namespace PersonalUltra.Infrastructure.Infrastructure.Migrations
{
    [DbContext(typeof(PersonalUltraDbContext))]
    partial class PersonalUltraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalUltra.Domain.Anamnesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("anamneses", "core");
                });

            modelBuilder.Entity("PersonalUltra.Domain.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("PersonalUltra.Domain.CoachMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt", "Id");

                    b.ToTable("messages", "coaching");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("conversations", "coaching");
                });

            modelBuilder.Entity("PersonalUltra.Domain.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("MealTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealTemplateId");

                    b.HasIndex("MemberId", "Date", "MealTemplateId")
                        .IsUnique();

                    b.ToTable("daily_logs", "nutrition");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryMuscleGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("exercises", "training");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("CarbsPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("FatPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ProteinPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("foods", "nutrition", t =>
                        {
                            t.HasCheckConstraint("CK_foods_nutrition_nonnegative", "\"CaloriesPer100g\" > 0 AND \"ProteinPer100g\" >= 0 AND \"CarbsPer100g\" >= 0 AND \"FatPer100g\" >= 0");
                        });
                });

            modelBuilder.Entity("PersonalUltra.Domain.MealTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("NutritionPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NutritionPlanId", "Sequence")
                        .IsUnique();

                    b.ToTable("meal_templates", "nutrition", t =>
                        {
                            t.HasCheckConstraint("CK_meal_templates_sequence_positive", "\"Sequence\" > 0");
                        });
                });

            modelBuilder.Entity("PersonalUltra.Domain.MealTemplateFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealTemplateId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityGrams")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealTemplateId");

                    b.ToTable("meal_template_foods", "nutrition", t =>
                        {
                            t.HasCheckConstraint("CK_meal_template_foods_quantity_positive", "\"QuantityGrams\" > 0");
                        });
                });

            modelBuilder.Entity("PersonalUltra.Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("members", "members");
                });

            modelBuilder.Entity("PersonalUltra.Domain.MemberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPainDescription")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentNotes")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HealthConditions")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("MovementRestrictions")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<string>("NutritionPreferences")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<string>("NutritionRestrictions")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("TrainingLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("profiles", "members");
                });

            modelBuilder.Entity("PersonalUltra.Domain.NutritionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CaloriesTarget")
                        .HasColumnType("integer");

                    b.Property<int>("CarbsGramsTarget")
                        .HasColumnType("integer");

                    b.Property<int>("FatGramsTarget")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProteinGramsTarget")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.ToTable("nutrition_plans", "nutrition", t =>
                        {
                            t.HasCheckConstraint("CK_nutrition_plans_targets_positive", "\"CaloriesTarget\" > 0 AND \"ProteinGramsTarget\" > 0 AND \"CarbsGramsTarget\" >= 0 AND \"FatGramsTarget\" >= 0");
                        });
                });

            modelBuilder.Entity("PersonalUltra.Domain.PainReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Intensity")
                        .HasColumnType("integer");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("PAIN_REASON_NOT_RECORDED");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SafetyLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "ReportedAt");

                    b.ToTable("pain_reports", "members");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ReviewDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("MemberId", "Status");

                    b.ToTable("plans", "plans");
                });

            modelBuilder.Entity("PersonalUltra.Domain.SetPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<int?>("RepsInReserve")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("WorkoutSessionExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionExerciseId", "ClientOperationId")
                        .IsUnique();

                    b.HasIndex("WorkoutSessionExerciseId", "SetNumber")
                        .IsUnique();

                    b.ToTable("set_performances", "training");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("students", "core");
                });

            modelBuilder.Entity("PersonalUltra.Domain.StudentInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.ToTable("student_invites", "core");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("trainers", "core");
                });

            modelBuilder.Entity("PersonalUltra.Domain.TrainerBranding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId")
                        .IsUnique();

                    b.ToTable("trainer_brandings", "core");
                });

            modelBuilder.Entity("PersonalUltra.Domain.TrainerStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrainerId", "StudentId")
                        .IsUnique();

                    b.ToTable("trainer_students", "core");
                });

            modelBuilder.Entity("PersonalUltra.Domain.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.ToTable("training_plans", "training");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WeightEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "RecordedAt");

                    b.ToTable("weight_entries", "progress");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ScheduledFor")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.HasIndex("MemberId", "ScheduledFor")
                        .IsUnique();

                    b.ToTable("workout_sessions", "training");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutSessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MaximumRepetitions")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumRepetitions")
                        .HasColumnType("integer");

                    b.Property<int>("PrescribedSets")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("workout_session_exercises", "training");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("workout_templates", "training");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutTemplateExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaximumRepetitions")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumRepetitions")
                        .HasColumnType("integer");

                    b.Property<int>("PrescribedSets")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId", "Sequence")
                        .IsUnique();

                    b.ToTable("workout_template_exercises", "training");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Anamnesis", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Student", "Student")
                        .WithOne("Anamnesis")
                        .HasForeignKey("PersonalUltra.Domain.Anamnesis", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PersonalUltra.Domain.CoachMessage", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Conversation", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PersonalUltra.Domain.DailyLog", b =>
                {
                    b.HasOne("PersonalUltra.Domain.MealTemplate", "MealTemplate")
                        .WithMany()
                        .HasForeignKey("MealTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalUltra.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealTemplate");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PersonalUltra.Domain.MealTemplate", b =>
                {
                    b.HasOne("PersonalUltra.Domain.NutritionPlan", "NutritionPlan")
                        .WithMany("Meals")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutritionPlan");
                });

            modelBuilder.Entity("PersonalUltra.Domain.MealTemplateFood", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalUltra.Domain.MealTemplate", "MealTemplate")
                        .WithMany("Foods")
                        .HasForeignKey("MealTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("MealTemplate");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Member", b =>
                {
                    b.HasOne("PersonalUltra.Domain.AuthUser", "AuthUser")
                        .WithOne("Member")
                        .HasForeignKey("PersonalUltra.Domain.Member", "AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("PersonalUltra.Domain.MemberProfile", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Member", "Member")
                        .WithOne("Profile")
                        .HasForeignKey("PersonalUltra.Domain.MemberProfile", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PersonalUltra.Domain.NutritionPlan", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Plan", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Member", "Member")
                        .WithMany("Plans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PersonalUltra.Domain.SetPerformance", b =>
                {
                    b.HasOne("PersonalUltra.Domain.WorkoutSessionExercise", "WorkoutSessionExercise")
                        .WithMany("SetPerformances")
                        .HasForeignKey("WorkoutSessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSessionExercise");
                });

            modelBuilder.Entity("PersonalUltra.Domain.StudentInvite", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Trainer", "Trainer")
                        .WithMany("Invites")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PersonalUltra.Domain.TrainerBranding", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Trainer", "Trainer")
                        .WithOne("Branding")
                        .HasForeignKey("PersonalUltra.Domain.TrainerBranding", "TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PersonalUltra.Domain.TrainerStudent", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Student", "Student")
                        .WithMany("Trainers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalUltra.Domain.Trainer", "Trainer")
                        .WithMany("Students")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PersonalUltra.Domain.TrainingPlan", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Plan", "Plan")
                        .WithOne("TrainingPlan")
                        .HasForeignKey("PersonalUltra.Domain.TrainingPlan", "PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WeightEntry", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutSession", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Member", "Member")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalUltra.Domain.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutSessionExercise", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalUltra.Domain.WorkoutSession", "WorkoutSession")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutTemplate", b =>
                {
                    b.HasOne("PersonalUltra.Domain.TrainingPlan", "TrainingPlan")
                        .WithMany("WorkoutTemplates")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("PersonalUltra.Domain.Exercise", "Exercise")
                        .WithMany("WorkoutTemplateExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalUltra.Domain.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("PersonalUltra.Domain.AuthUser", b =>
                {
                    b.Navigation("Member")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalUltra.Domain.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Exercise", b =>
                {
                    b.Navigation("WorkoutTemplateExercises");
                });

            modelBuilder.Entity("PersonalUltra.Domain.MealTemplate", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Member", b =>
                {
                    b.Navigation("Plans");

                    b.Navigation("Profile");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("PersonalUltra.Domain.NutritionPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Plan", b =>
                {
                    b.Navigation("TrainingPlan")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalUltra.Domain.Student", b =>
                {
                    b.Navigation("Anamnesis");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("PersonalUltra.Domain.Trainer", b =>
                {
                    b.Navigation("Branding");

                    b.Navigation("Invites");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("PersonalUltra.Domain.TrainingPlan", b =>
                {
                    b.Navigation("WorkoutTemplates");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutSessionExercise", b =>
                {
                    b.Navigation("SetPerformances");
                });

            modelBuilder.Entity("PersonalUltra.Domain.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
