using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using PersonalUltra.Infrastructure;
using PersonalUltra.StudentApi.Contracts;
namespace PersonalUltra.StudentApi.Endpoints;
public static class NutritionProgressEndpointExtensions
{
 public static void MapNutritionProgressApi(this WebApplication app){var api=app.MapGroup("/api/v1").RequireAuthorization();api.MapGet("/nutrition",async(PersonalUltraDbContext db,ClaimsPrincipal u,CancellationToken ct)=>{if(!Student(u,out var id))return ApiEndpointExtensions.ApiError("STUDENT_SESSION_REQUIRED","Use uma sessão válida.",403);var p=await db.NutritionPlans.AsNoTracking().Include(x=>x.Meals).ThenInclude(x=>x.Foods).SingleOrDefaultAsync(x=>x.StudentId==id,ct);return p is null?Results.Ok<StudentNutrition?>(null):Results.Ok(new StudentNutrition(p.Id,p.Name,p.Notes,p.Meals.OrderBy(x=>x.Sequence).Select(m=>new StudentMeal(m.Id,m.Name,m.Sequence,m.Notes,m.Foods.Select(f=>new StudentMealFood(f.FoodName,f.QuantityGrams)).ToArray())).ToArray()));});api.MapGet("/progress/weight",async(PersonalUltraDbContext db,ClaimsPrincipal u,CancellationToken ct)=>{if(!Student(u,out var id))return ApiEndpointExtensions.ApiError("STUDENT_SESSION_REQUIRED","Use uma sessão válida.",403);return Results.Ok(await db.WeightEntries.AsNoTracking().Where(x=>x.StudentId==id).OrderBy(x=>x.RecordedAt).Select(x=>new StudentWeight(x.Id,x.WeightKg,x.RecordedAt)).ToListAsync(ct));});api.MapPost("/progress/weight",async(AddWeightRequest r,PersonalUltraDbContext db,ClaimsPrincipal u,TimeProvider clock,CancellationToken ct)=>{if(!Student(u,out var id))return ApiEndpointExtensions.ApiError("STUDENT_SESSION_REQUIRED","Use uma sessão válida.",403);if(r.WeightKg is < 25 or > 400)return ApiEndpointExtensions.ApiError("VALIDATION_ERROR","Informe um peso entre 25 e 400 kg.",400);var e=new PersonalUltra.Domain.WeightEntry{Id=Guid.NewGuid(),StudentId=id,WeightKg=r.WeightKg,RecordedAt=r.RecordedAt??clock.GetUtcNow()};db.WeightEntries.Add(e);await db.SaveChangesAsync(ct);return Results.Ok(new StudentWeight(e.Id,e.WeightKg,e.RecordedAt));});api.MapGet("/coach/answer",async(string? question,PersonalUltraDbContext db,ClaimsPrincipal u,CancellationToken ct)=>{if(!Student(u,out var id))return ApiEndpointExtensions.ApiError("STUDENT_SESSION_REQUIRED","Use uma sessão válida.",403);var q=(question??"").Trim().ToLowerInvariant();var workout=await db.StudentWorkouts.AsNoTracking().Where(x=>x.StudentId==id).OrderBy(x=>x.RecommendedDay).FirstOrDefaultAsync(ct);var nutrition=await db.NutritionPlans.AsNoTracking().SingleOrDefaultAsync(x=>x.StudentId==id,ct);var answer=q.Contains("treino")&&workout is not null?$"Seu treino recomendado é {workout.Name}, com {await db.StudentWorkoutExercises.CountAsync(x=>x.StudentWorkoutId==workout.Id,ct)} exercícios.":q.Contains("aliment")&&nutrition is not null?$"Seu plano alimentar atual é {nutrition.Name}. Consulte as refeições cadastradas no app.":"Posso explicar seu treino, sua alimentação e os registros já cadastrados pelo seu personal.";return Results.Ok(new CoachAnswer(answer,["treino prescrito","alimentação cadastrada"]));});}
 static bool Student(ClaimsPrincipal u,out Guid id)=>Guid.TryParse(u.FindFirstValue(ClaimTypes.NameIdentifier),out id)&&u.FindFirstValue("subject")=="student";
}
