import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { useEffect } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { useMutation } from '@tanstack/react-query';
import { Button, Card, ErrorView, LoadingView } from '@/src/components/ui';
import { Screen, TopBar } from '@/src/components/layout';
import { colors, spacing, typography } from '@/src/design/tokens';
import { inviteApi, type StudentSession } from '@/src/features/student/invite/api';
import { useInviteSessionStore } from '@/src/features/student/invite/session-store';
import { queueSet, syncPendingSets } from '@/src/features/student/offline/training-db';

export default function StudentTrainingSessionScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const session = useInviteSessionStore((s) => s.session); const [workout, setWorkout] = useState<StudentSession>(); const [error, setError] = useState<string>(); const start = useMutation({ mutationFn: () => inviteApi.startWorkout(session!.accessToken, id!), onSuccess: setWorkout, onError: (e: Error) => setError(e.message) });
  useEffect(() => { if (session) void syncPendingSets((item) => inviteApi.completeSet(item.token, item.sessionId, item.exerciseId, item.input)); }, [session]);
  if (!session) { router.replace('/login'); return null; } if (!workout && !start.isPending && !start.isError) start.mutate(); if (start.isPending) return <LoadingView message="Preparando seu treino…" />; if (start.isError || error) return <ErrorView message={error ?? start.error?.message ?? 'Não foi possível iniciar este treino.'} onRetry={() => { setError(undefined); start.reset(); start.mutate(); }} />; if (!workout) return <LoadingView message="Preparando seu treino…" />;
  return <Screen style={styles.page}><TopBar eyebrow="TREINO EM ANDAMENTO" title={workout.workoutName} onBack={() => router.back()} /><Text style={styles.copy}>Registre as séries realizadas. O acompanhamento fica salvo conforme você avança.</Text>{workout.exercises.map((exercise) => <Exercise key={exercise.id} session={session.accessToken} workout={workout} exercise={exercise} />)}<Button onPress={async () => { await inviteApi.completeWorkout(session.accessToken, workout.sessionId); router.replace('/student-training'); }}>Concluir treino</Button></Screen>;
}
function Exercise({ session, workout, exercise }: { session: string; workout: StudentSession; exercise: StudentSession['exercises'][number] }) { const [sets, setSets] = useState(exercise.completedSets); const [weight, setWeight] = useState(''); const save = async () => { const input = { clientOperationId: `${workout.sessionId}-${exercise.id}-${sets + 1}`, setNumber: sets + 1, weightKg: Number(weight.replace(',', '.')) || 0, repetitions: exercise.repetitions }; try { await inviteApi.completeSet(session, workout.sessionId, exercise.id, input); } catch { await queueSet({ token: session, sessionId: workout.sessionId, exerciseId: exercise.id, input }); } setSets((value) => value + 1); setWeight(''); }; return <Card style={styles.card}><Text style={styles.title}>{exercise.sequence}. {exercise.name}</Text><Text style={styles.meta}>{sets}/{exercise.sets} séries · {exercise.repetitions} reps</Text><View style={styles.row}><TextInput value={weight} onChangeText={setWeight} keyboardType="decimal-pad" placeholder="Carga (kg)" placeholderTextColor={colors.textMuted} style={styles.input} /><Button variant="secondary" disabled={sets >= exercise.sets} onPress={() => void save()}>Salvar série</Button></View></Card>; }
const styles = StyleSheet.create({ page: { paddingVertical: spacing.xl, gap: spacing.lg }, copy: { ...typography.bodyMD, color: colors.textSecondary, lineHeight: 21 }, card: { gap: spacing.sm }, title: { ...typography.headingMD, color: colors.textPrimary }, meta: { ...typography.caption, color: colors.primary }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, input: { ...typography.bodyMD, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border, borderRadius: 12, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, flex: 1 } });
