import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useMutation } from '@tanstack/react-query';
import { Button, Card } from '@/src/components/ui';
import { Screen, TopBar } from '@/src/components/layout';
import { colors, spacing, typography } from '@/src/design/tokens';
import { inviteApi, type AnamnesisAnswers } from '@/src/features/student/invite/api';
import { useInviteSessionStore } from '@/src/features/student/invite/session-store';

const empty: AnamnesisAnswers = { goal: '', experienceLevel: '', trainingDaysPerWeek: 0, sessionDurationMinutes: 0, trainingLocation: '', equipmentNotes: '', heightCm: 0, weightKg: 0, healthConditions: '', movementRestrictions: '', currentPainDescription: '', nutritionPreferences: '', nutritionRestrictions: '' };

export default function InviteAnamnesisScreen() {
  const { token } = useLocalSearchParams<{ token: string }>();
  const session = useInviteSessionStore((state) => state.session);
  const [answers, setAnswers] = useState(empty);
  const save = useMutation({ mutationFn: (input: AnamnesisAnswers) => inviteApi.saveAnamnesis(session!.accessToken, input) });
  const complete = useMutation({ mutationFn: () => inviteApi.completeAnamnesis(session!.accessToken) });
  if (!session) { router.replace(`/invite/${token}`); return null; }
  const update = <K extends keyof AnamnesisAnswers>(key: K, value: AnamnesisAnswers[K]) => setAnswers((current) => ({ ...current, [key]: value }));
  const submit = async () => { try { await save.mutateAsync(answers); await complete.mutateAsync(); router.replace(`/invite/${token}/home`); } catch (error) { Alert.alert('Revise suas respostas', error instanceof Error ? error.message : 'Não foi possível salvar sua anamnese.'); } };
  return <Screen scroll={false} style={styles.page}><TopBar eyebrow="SEU PONTO DE PARTIDA" title="Anamnese" onBack={() => router.back()} /><Text style={styles.copy}>Estas informações ajudam seu personal a conhecer sua rotina. Elas não substituem orientação médica.</Text><ScrollView style={styles.scroll} contentContainerStyle={styles.form} keyboardShouldPersistTaps="handled"><Field label="Objetivo principal" value={answers.goal} onChangeText={(value) => update('goal', value)} placeholder="Ex.: Ganhar massa muscular" /><Field label="Experiência de treino" value={answers.experienceLevel} onChangeText={(value) => update('experienceLevel', value)} placeholder="Ex.: Estou começando agora" /><NumberField label="Dias disponíveis por semana" value={answers.trainingDaysPerWeek} onChange={(value) => update('trainingDaysPerWeek', value)} /><NumberField label="Duração média do treino (min)" value={answers.sessionDurationMinutes} onChange={(value) => update('sessionDurationMinutes', value)} /><Field label="Onde você treina?" value={answers.trainingLocation} onChangeText={(value) => update('trainingLocation', value)} placeholder="Ex.: Academia" /><Field label="Equipamentos disponíveis" value={answers.equipmentNotes} onChangeText={(value) => update('equipmentNotes', value)} placeholder="Ex.: Academia completa" /><NumberField label="Altura em cm" value={answers.heightCm} onChange={(value) => update('heightCm', value)} /><NumberField label="Peso aproximado em kg" value={answers.weightKg} onChange={(value) => update('weightKg', value)} /><Field label="Condições de saúde" value={answers.healthConditions} onChangeText={(value) => update('healthConditions', value)} placeholder="Escreva 'Nenhuma' se não houver" multiline /><Field label="Limitações de movimento" value={answers.movementRestrictions} onChangeText={(value) => update('movementRestrictions', value)} placeholder="Escreva 'Nenhuma' se não houver" multiline /><Field label="Dor atual" value={answers.currentPainDescription} onChangeText={(value) => update('currentPainDescription', value)} placeholder="Escreva 'Sem dor' se não houver" multiline /><Field label="Preferências alimentares" value={answers.nutritionPreferences} onChangeText={(value) => update('nutritionPreferences', value)} placeholder="Ex.: 4 refeições por dia" multiline /><Field label="Restrições alimentares" value={answers.nutritionRestrictions} onChangeText={(value) => update('nutritionRestrictions', value)} placeholder="Escreva 'Nenhuma' se não houver" multiline /><Button loading={save.isPending || complete.isPending} onPress={() => void submit()}>Enviar para meu personal</Button></ScrollView></Screen>;
}

function Field({ label, value, onChangeText, placeholder, multiline = false }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; multiline?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.textMuted} multiline={multiline} style={[styles.input, multiline && styles.multiline]} /></View>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <Field label={label} value={value ? String(value) : ''} onChangeText={(text) => onChange(Number(text.replace(',', '.')) || 0)} placeholder="Informe um valor" />; }

const styles = StyleSheet.create({ page: { paddingVertical: spacing.xl, gap: spacing.md }, copy: { ...typography.bodyMD, color: colors.textSecondary, lineHeight: 21 }, scroll: { flex: 1 }, form: { gap: spacing.md, paddingBottom: spacing.xxl }, field: { gap: spacing.xs }, label: { ...typography.caption, color: colors.textSecondary }, input: { ...typography.bodyMD, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: spacing.md, minHeight: 52 }, multiline: { minHeight: 88, textAlignVertical: 'top' } });
