import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, ErrorView, ListItem, LoadingView, SearchField, Tag } from '@/src/components/ui';
import { Screen, TopBar } from '@/src/components/layout';
import { colors, spacing, typography } from '@/src/design/tokens';
import { feedback } from '@/src/platform/feedback';
import { useTrainerStudent } from '@/src/features/trainer/students/hooks';
import { useApplyNutritionTemplate, useNutritionTemplate, useNutritionTemplates, useTrainerNutrition } from './hooks';

export function ApplyNutritionTemplateScreen() {
  const { studentId = '' } = useLocalSearchParams<{ studentId: string }>(); const [selected, setSelected] = useState<string>(); const [search, setSearch] = useState('');
  const student = useTrainerStudent(studentId); const current = useTrainerNutrition(studentId); const templates = useNutritionTemplates(); const detail = useNutritionTemplate(selected ?? '', Boolean(selected)); const apply = useApplyNutritionTemplate(studentId);
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase('pt-BR'); return (templates.data ?? []).filter((item) => !term || `${item.name} ${item.notes}`.toLocaleLowerCase('pt-BR').includes(term)); }, [search, templates.data]);
  if (!studentId) return <ErrorView message="Não foi possível identificar o aluno." />;
  if (student.isLoading || current.isLoading || templates.isLoading) return <LoadingView message="Preparando os presets…" />;
  if (student.isError) return <ErrorView message={student.error.message} onRetry={() => student.refetch()} />;
  if (current.isError) return <ErrorView message={current.error.message} onRetry={() => current.refetch()} />;
  if (templates.isError) return <ErrorView message={templates.error.message} onRetry={() => templates.refetch()} />;
  if (selected && detail.isLoading) return <LoadingView message="Abrindo o preset…" />;
  if (selected && detail.isError) return <ErrorView message={detail.error.message} onRetry={() => detail.refetch()} />;
  const applyNow = () => { if (!selected) return; const replaceExisting = Boolean(current.data); const execute = () => apply.mutate({ templateId: selected, replaceExisting }, { onSuccess: (result) => { feedback.success(); Alert.alert('Alimentação adicionada', `${result.name} foi disponibilizado para ${student.data!.firstName}.`); router.replace({ pathname: '/trainer/students/[id]', params: { id: studentId, section: 'nutrition' } }); } }); if (replaceExisting) Alert.alert('Substituir plano atual?', `O conteúdo atual de ${student.data!.firstName} será substituído por uma cópia deste preset.`, [{ text: 'Cancelar', style: 'cancel' }, { text: 'Substituir', style: 'destructive', onPress: execute }]); else execute(); };
  if (selected && detail.data) return <Screen withinTabs style={styles.page}><TopBar eyebrow="ETAPA 2 DE 2 · REVISAR" title={detail.data.name} onBack={() => setSelected(undefined)} action={<Tag tone="neutral">PRESET</Tag>} /><Text style={styles.copy}>Confira as refeições antes de disponibilizar para {student.data!.firstName}.</Text>{current.data ? <Card style={styles.warning}><Text style={styles.warningTitle}>Este aluno já possui um plano</Text><Text style={styles.copy}>{current.data.name} será substituído somente após sua confirmação.</Text></Card> : null}<MealCards meals={detail.data.meals ?? []} />{apply.error ? <Card style={styles.warning}><Text accessibilityRole="alert" style={styles.warningTitle}>Não foi possível aplicar o preset</Text><Text style={styles.copy}>{apply.error.message}</Text></Card> : null}<Button loading={apply.isPending} disabled={!detail.data.meals?.length} onPress={applyNow}>{current.data ? 'Substituir usando este preset' : 'Usar este preset'}</Button><Button variant="ghost" onPress={() => setSelected(undefined)}>Escolher outro preset</Button></Screen>;
  return <Screen withinTabs style={styles.page}><TopBar eyebrow="ETAPA 1 DE 2 · ESCOLHER" title="Adicionar por preset" onBack={() => router.back()} /><Card style={styles.context}><Text style={styles.label}>ALIMENTAÇÃO PARA</Text><Text style={styles.title}>{student.data!.firstName} {student.data!.lastName}</Text><Text style={styles.copy}>Escolha uma estrutura e revise as refeições antes de aplicar.</Text></Card>{templates.data!.length ? <SearchField value={search} onChangeText={setSearch} placeholder="Buscar preset…" accessibilityLabel="Buscar preset para o aluno" /> : null}{!templates.data!.length ? <EmptyState status="SEM PRESETS DISPONÍVEIS" symbol="+" title="Crie um preset antes de usar este atalho." message="Depois, volte ao aluno para aplicá-lo." actionLabel="Abrir biblioteca" onAction={() => router.push('/trainer/nutrition/templates')} /> : !filtered.length ? <EmptyState variant="inline" status="NENHUM RESULTADO" symbol="⌕" title="Não encontramos esse preset." message="Tente outro nome." actionLabel="Limpar busca" onAction={() => setSearch('')} /> : <View style={styles.list}>{filtered.map((item) => <ListItem key={item.id} title={item.name} metadata={`${item.mealCount ?? 0} refeições · ${item.foodCount ?? 0} itens`} description={item.notes || undefined} actionLabel="Revisar" disabled={!item.mealCount} onPress={() => setSelected(item.id)} />)}</View>}</Screen>;
}
function MealCards({ meals }: { meals: NonNullable<ReturnType<typeof useNutritionTemplate>['data']>['meals'] extends infer T ? NonNullable<T> : never }) { return <View style={styles.list}>{meals.map((meal) => <Card key={meal.id} style={styles.meal}><Text style={styles.label}>REFEIÇÃO {meal.sequence}</Text><Text style={styles.title}>{meal.name}</Text>{meal.notes ? <Text style={styles.copy}>{meal.notes}</Text> : null}{meal.foods.map((food) => <View key={food.id} style={styles.food}><Text style={styles.foodName}>{food.foodName}</Text><Text style={styles.quantity}>{food.quantity} {food.unit}</Text></View>)}</Card>)}</View>; }
const styles = StyleSheet.create({ page: { paddingVertical: spacing.xl, gap: spacing.md }, copy: { ...typography.bodyMD, color: colors.textSecondary, lineHeight: 21 }, context: { gap: spacing.xs, borderColor: colors.primary }, label: { ...typography.caption, color: colors.primary, letterSpacing: .8 }, title: { ...typography.headingMD, color: colors.textPrimary }, list: { gap: spacing.sm }, warning: { gap: spacing.xs, borderColor: colors.danger }, warningTitle: { ...typography.headingMD, color: colors.danger }, meal: { gap: spacing.sm }, food: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm, paddingTop: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border }, foodName: { ...typography.bodyMD, color: colors.textPrimary, flex: 1 }, quantity: { ...typography.caption, color: colors.primary } });
