import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, ErrorView, LoadingView, SearchField } from '@/src/components/ui';
import { Screen, TopBar } from '@/src/components/layout';
import { colors, spacing, typography } from '@/src/design/tokens';
import { useNutritionTemplates } from './hooks';

export function NutritionTemplatesScreen() {
  const { returnStudentId } = useLocalSearchParams<{ returnStudentId?: string }>();
  const query = useNutritionTemplates(); const [search, setSearch] = useState('');
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase('pt-BR'); return (query.data ?? []).filter((item) => !term || `${item.name} ${item.notes}`.toLocaleLowerCase('pt-BR').includes(term)); }, [query.data, search]);
  const back = () => returnStudentId ? router.replace({ pathname: '/trainer/students/[id]', params: { id: returnStudentId, section: 'nutrition' } }) : router.replace('/trainer/nutrition');
  const createPreset = () => router.push({ pathname: '/trainer/nutrition/templates/[id]', params: { id: 'new', draftKey: String(Date.now()), ...(returnStudentId ? { returnStudentId } : {}) } });
  if (query.isLoading) return <LoadingView message="Carregando presets de alimentação…" />;
  if (query.isError) return <ErrorView message={query.error.message} onRetry={() => query.refetch()} />;
  return <Screen withinTabs style={styles.page}><TopBar eyebrow="BIBLIOTECA DO PERSONAL" title="Presets de refeição" onBack={back} /><Text style={styles.copy}>Salve combinações como “Café com ovos” e reutilize cada refeição nos planos dos alunos.</Text><Button onPress={createPreset}>+ Novo preset de refeição</Button>{query.data!.length ? <SearchField value={search} onChangeText={setSearch} placeholder="Buscar refeição…" accessibilityLabel="Buscar preset de refeição" /> : null}{!query.data!.length ? <EmptyState status="BIBLIOTECA VAZIA" symbol="+" title="Crie seu primeiro preset de refeição." message="Monte uma combinação de alimentos para reutilizar quando criar uma alimentação." actionLabel="Criar preset" onAction={createPreset} /> : !filtered.length ? <EmptyState variant="inline" status="NENHUM RESULTADO" symbol="⌕" title="Não encontramos essa refeição." message="Tente outro nome ou limpe a busca." actionLabel="Limpar busca" onAction={() => setSearch('')} /> : <View style={styles.list}>{filtered.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`Editar preset ${item.name}`} onPress={() => router.push({ pathname: '/trainer/nutrition/templates/[id]', params: { id: item.id, ...(returnStudentId ? { returnStudentId } : {}) } })} style={({ pressed }) => pressed && styles.pressed}><Card style={styles.presetCard}><Text style={styles.title}>{item.name}</Text>{item.notes ? <Text style={styles.notes}>{item.notes}</Text> : null}<View style={styles.foods}>{(item.foodNames ?? []).slice(0, 4).map((food, index) => <View key={`${index}-${food}`} style={styles.foodRow}><Text style={styles.bullet}>•</Text><Text style={styles.foodName}>{food}</Text></View>)}{(item.foodNames?.length ?? 0) > 4 ? <Text style={styles.more}>+ {(item.foodNames?.length ?? 0) - 4} outros itens</Text> : null}</View><Text style={styles.action}>Editar preset →</Text></Card></Pressable>)}</View>}</Screen>;
}
const styles = StyleSheet.create({ page: { paddingVertical: spacing.xl, gap: spacing.md }, copy: { ...typography.bodyMD, color: colors.textSecondary, lineHeight: 21 }, list: { gap: spacing.sm }, pressed: { opacity: .76 }, presetCard: { gap: spacing.sm }, title: { ...typography.headingMD, color: colors.textPrimary }, notes: { ...typography.bodyMD, color: colors.textSecondary, lineHeight: 21 }, foods: { gap: spacing.xs, paddingTop: spacing.xs, borderTopWidth: 1, borderTopColor: colors.border }, foodRow: { flexDirection: 'row', gap: spacing.sm }, bullet: { ...typography.bodyMD, color: colors.primary }, foodName: { ...typography.bodyMD, color: colors.titaniumLight, flex: 1 }, more: { ...typography.caption, color: colors.textMuted }, action: { ...typography.caption, color: colors.primary, alignSelf: 'flex-end' } });
