import { Redirect, router } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, EmptyState, ErrorView, LoadingView } from '@/src/components/ui';
import { Screen, TopBar } from '@/src/components/layout';
import { colors, radius, spacing, typography } from '@/src/design/tokens';
import { ProgressBarChart } from '@/src/features/student/components/progress-bar-chart';
import { inviteApi, type StudentHydration, type StudentWeight } from '@/src/features/student/invite/api';
import { useInviteSessionStore } from '@/src/features/student/invite/session-store';

const date = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' });
const shortDate = new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit' });
const time = new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' });
const number = (value: string) => Number(value.trim().replace(',', '.'));
const dayKey = (value: string | Date) => { const d = new Date(value); return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`; };
const ml = (value: number) => value >= 1000 ? `${(value / 1000).toLocaleString('pt-BR', { maximumFractionDigits: 1 })} L` : `${value} ml`;

function Editor({ value, onChange, placeholder, submit, onSubmit, onCancel, busy }: { value: string; onChange: (value: string) => void; placeholder: string; submit: string; onSubmit: () => void; onCancel?: () => void; busy: boolean }) {
  return <View style={styles.editor}><TextInput value={value} onChangeText={onChange} keyboardType="decimal-pad" placeholder={placeholder} placeholderTextColor={colors.textMuted} style={styles.input} /><View style={styles.actions}>{onCancel ? <Button variant="secondary" style={styles.flexButton} onPress={onCancel}>Cancelar</Button> : null}<Button style={styles.flexButton} loading={busy} disabled={!value.trim()} onPress={onSubmit}>{submit}</Button></View></View>;
}
function HistoryEntry({ title, subtitle, onEdit, onDelete, busy }: { title: string; subtitle: string; onEdit: () => void; onDelete: () => void; busy: boolean }) {
  return <Card style={styles.entry}><View style={styles.entryCopy}><Text style={styles.value}>{title}</Text><Text style={styles.copy}>{subtitle}</Text></View><View style={styles.entryActions}><Pressable accessibilityRole="button" accessibilityLabel={`Editar ${title}`} onPress={onEdit}><Text style={styles.edit}>Editar</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Excluir ${title}`} disabled={busy} onPress={onDelete}><Text style={styles.remove}>Excluir</Text></Pressable></View></Card>;
}

export function StudentProgressScreen() {
  const session = useInviteSessionStore((state) => state.session);
  const queryClient = useQueryClient();
  const [weightValue, setWeightValue] = useState(''); const [hydrationValue, setHydrationValue] = useState('');
  const [editingWeight, setEditingWeight] = useState<StudentWeight>(); const [editingHydration, setEditingHydration] = useState<StudentHydration>();
  const weight = useQuery({ queryKey: ['student', session?.studentId, 'weight'], queryFn: () => inviteApi.weight(session!.accessToken), enabled: Boolean(session) });
  const hydration = useQuery({ queryKey: ['student', session?.studentId, 'hydration'], queryFn: () => inviteApi.hydration(session!.accessToken), enabled: Boolean(session) });
  const refresh = () => Promise.all(['weight', 'hydration'].map((key) => queryClient.invalidateQueries({ queryKey: ['student', session?.studentId, key] })));
  const addWeight = useMutation({ mutationFn: () => inviteApi.addWeight(session!.accessToken, number(weightValue)), onSuccess: () => { setWeightValue(''); void refresh(); } });
  const saveWeight = useMutation({ mutationFn: () => inviteApi.updateWeight(session!.accessToken, editingWeight!.id, number(weightValue), editingWeight!.recordedAt), onSuccess: () => { setEditingWeight(undefined); setWeightValue(''); void refresh(); } });
  const deleteWeight = useMutation({ mutationFn: (entry: StudentWeight) => inviteApi.deleteWeight(session!.accessToken, entry.id), onSuccess: () => void refresh() });
  const addHydration = useMutation({ mutationFn: (amount: number) => inviteApi.addHydration(session!.accessToken, amount), onSuccess: () => { setHydrationValue(''); void refresh(); } });
  const saveHydration = useMutation({ mutationFn: () => inviteApi.updateHydration(session!.accessToken, editingHydration!.id, Math.round(number(hydrationValue)), editingHydration!.recordedAt), onSuccess: () => { setEditingHydration(undefined); setHydrationValue(''); void refresh(); } });
  const deleteHydration = useMutation({ mutationFn: (entry: StudentHydration) => inviteApi.deleteHydration(session!.accessToken, entry.id), onSuccess: () => void refresh() });
  const hydrationDays = useMemo(() => { const totals = new Map<string, { id: string; amount: number; label: string }>(); (hydration.data ?? []).forEach((entry) => { const key = dayKey(entry.recordedAt); const old = totals.get(key); totals.set(key, { id: key, amount: (old?.amount ?? 0) + entry.amountMl, label: shortDate.format(new Date(entry.recordedAt)) }); }); return [...totals.values()]; }, [hydration.data]);
  if (!session) return <Redirect href="/login" />;
  if (weight.isLoading || hydration.isLoading) return <LoadingView message="Carregando seu progresso…" />;
  if (weight.isError || hydration.isError) return <ErrorView message={weight.error?.message ?? hydration.error?.message ?? 'Não foi possível carregar seu progresso.'} onRetry={() => { void weight.refetch(); void hydration.refetch(); }} />;
  const weights = weight.data!; const water = hydration.data!;
  const today = water.filter((entry) => dayKey(entry.recordedAt) === dayKey(new Date())).reduce((total, entry) => total + entry.amountMl, 0);
  const confirm = (title: string, message: string, action: () => void) => Alert.alert(title, message, [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: action }]);
  return <Screen style={styles.page}><TopBar eyebrow="PROGRESSO" title="Seu acompanhamento" onBack={() => router.back()} />
    <View style={styles.section}><Text style={styles.sectionTitle}>Peso</Text><Card style={styles.card}><Text style={styles.title}>{editingWeight ? 'Corrigir medida' : 'Registrar nova medida'}</Text><Text style={styles.copy}>{editingWeight ? `Registro de ${date.format(new Date(editingWeight.recordedAt))}.` : 'Use uma medida atual para acompanhar sua evolução.'}</Text><Editor value={weightValue} onChange={setWeightValue} placeholder="Peso em kg" submit={editingWeight ? 'Salvar correção' : 'Salvar peso'} busy={addWeight.isPending || saveWeight.isPending} onCancel={editingWeight ? () => { setEditingWeight(undefined); setWeightValue(''); } : undefined} onSubmit={() => editingWeight ? saveWeight.mutate() : addWeight.mutate()} /></Card>
      {weights.length >= 2 ? <Card style={styles.card}><Text style={styles.eyebrow}>EVOLUÇÃO DE PESO</Text><ProgressBarChart points={weights.map((entry) => ({ id: entry.id, value: entry.weightKg, label: shortDate.format(new Date(entry.recordedAt)), accessibilityLabel: `${entry.weightKg} kg em ${date.format(new Date(entry.recordedAt))}` }))} valueLabel={(value) => `${value} kg`} /></Card> : <EmptyState variant="inline" status="LINHA EM CONSTRUÇÃO" title={weights.length ? 'Mais uma medida mostra sua evolução.' : 'Seu primeiro registro começa por aqui.'} message="O gráfico será criado somente com as suas medidas reais." />}
      <View style={styles.list}>{weights.slice().reverse().map((entry) => <HistoryEntry key={entry.id} title={`${entry.weightKg} kg`} subtitle={date.format(new Date(entry.recordedAt))} busy={deleteWeight.isPending} onEdit={() => { setEditingWeight(entry); setWeightValue(String(entry.weightKg).replace('.', ',')); }} onDelete={() => confirm('Excluir esta medida?', 'Este registro será removido do seu histórico.', () => deleteWeight.mutate(entry))} />)}</View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Hidratação</Text><Card style={styles.card}><Text style={styles.eyebrow}>HOJE</Text><Text style={styles.hydration}>{ml(today)}</Text><Text style={styles.copy}>Registre o que você bebeu. Este é um histórico pessoal, sem meta automática.</Text><View style={styles.actions}><Button variant="secondary" style={styles.flexButton} disabled={addHydration.isPending} onPress={() => addHydration.mutate(500)}>+500 ml</Button><Button variant="secondary" style={styles.flexButton} disabled={addHydration.isPending} onPress={() => addHydration.mutate(1000)}>+1 L</Button></View><Text style={styles.title}>{editingHydration ? 'Corrigir registro' : 'Outro valor'}</Text><Editor value={hydrationValue} onChange={setHydrationValue} placeholder="Quantidade em ml" submit={editingHydration ? 'Salvar correção' : 'Adicionar água'} busy={addHydration.isPending || saveHydration.isPending} onCancel={editingHydration ? () => { setEditingHydration(undefined); setHydrationValue(''); } : undefined} onSubmit={() => editingHydration ? saveHydration.mutate() : addHydration.mutate(Math.round(number(hydrationValue)))} /></Card>
      {hydrationDays.length >= 2 ? <Card style={styles.card}><Text style={styles.eyebrow}>HISTÓRICO DE HIDRATAÇÃO</Text><ProgressBarChart accent={colors.signalGreen} points={hydrationDays.map((entry) => ({ id: entry.id, value: entry.amount, label: entry.label, accessibilityLabel: `${entry.amount} ml em ${entry.label}` }))} valueLabel={ml} /></Card> : <EmptyState variant="inline" status="HISTÓRICO EM CONSTRUÇÃO" title={hydrationDays.length ? 'Registre em outro dia para ver seu gráfico.' : 'Sua hidratação começa com o primeiro registro.'} message="Os totais por dia aparecerão aqui conforme você registrar sua água." />}
      <View style={styles.list}>{water.slice().reverse().map((entry) => <HistoryEntry key={entry.id} title={`${entry.amountMl} ml`} subtitle={`${date.format(new Date(entry.recordedAt))} às ${time.format(new Date(entry.recordedAt))}`} busy={deleteHydration.isPending} onEdit={() => { setEditingHydration(entry); setHydrationValue(String(entry.amountMl)); }} onDelete={() => confirm('Excluir este registro?', 'Este registro será removido do seu histórico.', () => deleteHydration.mutate(entry))} />)}</View></View>
  </Screen>;
}

const styles = StyleSheet.create({ page: { paddingVertical: spacing.xl, gap: spacing.xl }, section: { gap: spacing.sm }, sectionTitle: { ...typography.headingLG, color: colors.textPrimary }, card: { gap: spacing.md }, eyebrow: { ...typography.caption, color: colors.primary, letterSpacing: 1 }, title: { ...typography.headingMD, color: colors.textPrimary }, copy: { ...typography.bodyMD, color: colors.textSecondary, lineHeight: 21 }, hydration: { ...typography.metricXL, color: colors.signalGreen }, editor: { gap: spacing.sm }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, flexButton: { flexGrow: 1, flexBasis: 140 }, input: { ...typography.bodyMD, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, minHeight: 52 }, list: { gap: spacing.sm }, entry: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md }, entryCopy: { flex: 1, minWidth: 130, gap: spacing.xxs }, value: { ...typography.headingMD, color: colors.textPrimary }, entryActions: { flexDirection: 'row', gap: spacing.md }, edit: { ...typography.caption, color: colors.primary }, remove: { ...typography.caption, color: colors.danger } });
