import { router } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, ErrorView, ListItem, LoadingView, Tag } from '@/src/components/ui';
import { Screen } from '@/src/components/layout';
import { colors, spacing, typography } from '@/src/design/tokens';
import { useTrainerDashboard } from '@/src/features/trainer/dashboard/hooks';

export default function TrainerHomeScreen() {
  const dashboard = useTrainerDashboard();
  if (dashboard.isLoading) return <LoadingView message="Abrindo seu painel…" />;
  if (dashboard.isError) return <ErrorView message={dashboard.error.message} onRetry={() => dashboard.refetch()} />;
  const data = dashboard.data!;
  return <Screen style={styles.page}><View style={styles.header}><Text style={styles.eyebrow}>PAINEL DO PERSONAL</Text><Text style={styles.title}>Olá, {data.trainerName.split(' ')[0]}.</Text><Text style={styles.copy}>Acompanhe o início da jornada dos seus alunos.</Text></View><View style={styles.metrics}><Card style={styles.metric}><Text style={styles.metricValue}>{data.activeStudents}</Text><Text style={styles.metricLabel}>Alunos ativos</Text></Card><Card style={styles.metric}><Text style={styles.metricValue}>{data.pendingAnamneses}</Text><Text style={styles.metricLabel}>Anamneses pendentes</Text></Card></View><Button onPress={() => router.push('/trainer/invite')}>Convidar novo aluno</Button><View style={styles.section}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Alunos recentes</Text><Button variant="ghost" style={styles.viewAll} onPress={() => router.push('/trainer/students')}>Ver todos</Button></View>{data.recentStudents.length === 0 ? <EmptyState variant="inline" status="COMECE SUA CARTEIRA" title="Seus alunos aparecerão aqui." message="Envie o primeiro convite para começar o acompanhamento." actionLabel="Convidar aluno" onAction={() => router.push('/trainer/invite')} /> : data.recentStudents.map((student) => <ListItem key={student.studentId} title={`${student.firstName} ${student.lastName}`} metadata={student.email ?? 'E-mail não informado'} badge={<Tag tone={student.anamnesisStatus === 'Completed' ? 'success' : 'neutral'}>{student.anamnesisStatus === 'Completed' ? 'CONCLUÍDA' : student.anamnesisStatus === 'InProgress' ? 'EM PREENCHIMENTO' : 'AGUARDANDO ANAMNESE'}</Tag>} onPress={() => router.push({ pathname: '/trainer/students/[id]', params: { id: student.studentId } })} accessibilityLabel={`Abrir ${student.firstName} ${student.lastName}`} />)}</View><View style={styles.section}><Text style={styles.sectionTitle}>Atividade recente</Text>{data.recentActivities.length === 0 ? <EmptyState variant="inline" status="SEM NOVIDADES" title="A atividade recente está tranquila." message="Conclusões de anamnese aparecerão aqui para facilitar seu acompanhamento." /> : data.recentActivities.map((activity) => <ListItem key={`${activity.type}-${activity.studentId}-${activity.occurredAt}`} title={`${activity.studentName} concluiu a anamnese`} metadata={new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(activity.occurredAt))} />)}</View><Button variant="ghost" onPress={() => router.replace('/demo-role-switch')}>Trocar contexto demo</Button></Screen>;
}
const styles = StyleSheet.create({ page: { paddingVertical: spacing.xl, gap: spacing.xl }, header: { gap: spacing.xs }, eyebrow: { ...typography.caption, color: colors.primary, letterSpacing: 1 }, title: { ...typography.displayLG, color: colors.textPrimary }, copy: { ...typography.bodyMD, color: colors.textSecondary, lineHeight: 21 }, metrics: { flexDirection: 'row', gap: spacing.sm }, metric: { flex: 1, gap: spacing.xxs, backgroundColor: colors.surfaceElevated }, metricValue: { ...typography.metricXL, color: colors.signalGreen }, metricLabel: { ...typography.bodyMD, color: colors.textSecondary }, section: { gap: spacing.xs }, sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.xxs }, sectionTitle: { ...typography.headingMD, color: colors.textPrimary }, viewAll: { minHeight: 36, paddingHorizontal: spacing.sm } });
