import { router } from 'expo-router';
import { useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, ErrorView, LoadingView } from '@/src/components/ui';
import { Screen, TopBar } from '@/src/components/layout';
import { colors, spacing, typography } from '@/src/design/tokens';
import { useCreateTrainerTemplate, useDuplicateTrainerTemplate, useTrainerTemplates } from '@/src/features/trainer/training/hooks';

export default function TrainerTrainingScreen() {
  const templates = useTrainerTemplates(); const create = useCreateTrainerTemplate(); const duplicate = useDuplicateTrainerTemplate(); const [name, setName] = useState(''); const [exercise, setExercise] = useState(''); const [sets, setSets] = useState('3'); const [repetitions, setRepetitions] = useState('10'); const [rest, setRest] = useState('60');
  if (templates.isLoading) return <LoadingView message="Carregando seus treinos…" />;
  if (templates.isError) return <ErrorView message={templates.error.message} onRetry={() => templates.refetch()} />;
  const createTemplate = () => { if (!name.trim() || !exercise.trim()) return; create.mutate({ name: name.trim(), notes: '', exercises: [{ name: exercise.trim(), sequence: 1, sets: Number(sets), repetitions: Number(repetitions), restSeconds: Number(rest), notes: '' }] }); setName(''); setExercise(''); };
  return <Screen style={styles.page}><TopBar eyebrow="PRESCRIÇÃO" title="Meus treinos" onBack={() => router.back()} /><Text style={styles.copy}>Crie modelos reutilizáveis e aplique uma cópia ao aluno.</Text><Card style={styles.create}><Text style={styles.cardTitle}>Novo modelo</Text><TextInput value={name} onChangeText={setName} placeholder="Nome do treino" placeholderTextColor={colors.textMuted} style={styles.input} /><TextInput value={exercise} onChangeText={setExercise} placeholder="Primeiro exercício" placeholderTextColor={colors.textMuted} style={styles.input} /><View style={styles.row}><TextInput value={sets} onChangeText={setSets} keyboardType="number-pad" placeholder="Séries" placeholderTextColor={colors.textMuted} style={styles.smallInput} /><TextInput value={repetitions} onChangeText={setRepetitions} keyboardType="number-pad" placeholder="Reps" placeholderTextColor={colors.textMuted} style={styles.smallInput} /><TextInput value={rest} onChangeText={setRest} keyboardType="number-pad" placeholder="Descanso" placeholderTextColor={colors.textMuted} style={styles.smallInput} /></View><Button loading={create.isPending} disabled={!name.trim() || !exercise.trim()} onPress={createTemplate}>Criar treino</Button></Card><View style={styles.list}>{templates.data!.map((item) => <Card key={item.id} style={styles.item}><Text style={styles.itemTitle}>{item.name}</Text><Text style={styles.copy}>{item.exerciseCount ?? 0} exercícios</Text><View style={styles.actions}><Button variant="secondary" onPress={() => duplicate.mutate(item.id)}>Duplicar</Button><Button variant="ghost" onPress={() => router.push({ pathname: '/trainer/training/[id]', params: { id: item.id } })}>Editar</Button></View></Card>)}</View></Screen>;
}
const styles = StyleSheet.create({ page: { paddingVertical: spacing.xl, gap: spacing.lg }, copy: { ...typography.bodyMD, color: colors.textSecondary }, create: { gap: spacing.md }, cardTitle: { ...typography.headingMD, color: colors.textPrimary }, input: { ...typography.bodyMD, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: spacing.md }, row: { flexDirection: 'row', gap: spacing.sm }, smallInput: { flex: 1, ...typography.bodyMD, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: spacing.sm }, list: { gap: spacing.sm }, item: { gap: spacing.xs }, itemTitle: { ...typography.headingMD, color: colors.textPrimary }, actions: { flexDirection: 'row', gap: spacing.sm } });
