namespace PersonalUltra.TrainerApi.Contracts;
public sealed record MealFoodAlternativeInput(string? FoodName, decimal Quantity, string? Unit, int Sequence, string? Notes);
public sealed record MealFoodInput(string? FoodName, decimal Quantity, string? Unit, int Sequence, IReadOnlyList<MealFoodAlternativeInput?>? Alternatives = null);
public sealed record MealInput(string? Name, int Sequence, string? Notes, IReadOnlyList<MealFoodInput?>? Foods);
public sealed record NutritionDailyGoalsInput(decimal? Calories, decimal? ProteinGrams, decimal? CarbohydratesGrams, decimal? FatGrams);
public sealed record NutritionDailyGoalsResponse(decimal? Calories, decimal? ProteinGrams, decimal? CarbohydratesGrams, decimal? FatGrams);
public sealed record NutritionPlanRequest(string? Name, string? Notes, IReadOnlyList<MealInput?>? Meals, NutritionDailyGoalsInput? DailyGoals = null);
public sealed record NutritionPlanResponse(Guid Id, string Name, string Notes, DateTimeOffset UpdatedAt, string ResponsibleTrainerName, IReadOnlyList<MealResponse> Meals, NutritionDailyGoalsResponse? DailyGoals = null);
public sealed record MealResponse(Guid Id, string Name, int Sequence, string Notes, IReadOnlyList<MealFoodResponse> Foods);
public sealed record MealFoodAlternativeResponse(Guid Id, string FoodName, decimal Quantity, string Unit, int Sequence, string Notes);
public sealed record MealFoodResponse(Guid Id, string FoodName, decimal Quantity, string Unit, int Sequence, IReadOnlyList<MealFoodAlternativeResponse> Alternatives);
public sealed record WeightResponse(Guid Id, decimal WeightKg, DateTimeOffset RecordedAt);
public sealed record NutritionMealTemplateRequest(string? Name, string? Notes, IReadOnlyList<MealFoodInput?>? Foods);
public sealed record NutritionMealTemplateSummary(Guid Id, string Name, string Notes, int ItemCount, IReadOnlyList<string> FoodNames, DateTimeOffset CreatedAt, DateTimeOffset UpdatedAt);
public sealed record NutritionMealTemplateResponse(Guid Id, string Name, string Notes, DateTimeOffset CreatedAt, DateTimeOffset UpdatedAt, IReadOnlyList<NutritionMealTemplateFoodResponse> Foods);
public sealed record NutritionMealTemplateFoodResponse(Guid Id, string FoodName, decimal Quantity, string Unit, int Sequence, IReadOnlyList<MealFoodAlternativeResponse> Alternatives);
public sealed record ApplyNutritionMealTemplateResponse(Guid PlanId, Guid StudentId, Guid MealId, string MealName, DateTimeOffset UpdatedAt, int MealCount);
