namespace PersonalUltra.TrainerApi.Contracts;

public sealed record WorkoutTemplateSummary(Guid Id, string Name, string Notes, int ExerciseCount, DateTimeOffset UpdatedAt, IReadOnlyList<string> MuscleGroups);
public sealed record WorkoutTemplateExerciseInput(Guid ExerciseId, int Sequence, int Sets, int RepetitionsMin, int RepetitionsMax, int RestSeconds, string? Notes, string? TrackingMode = null, int? TargetDurationSeconds = null);
public sealed record WorkoutTemplateExerciseResponse(Guid ExerciseId, string Name, string PrimaryMuscleGroup, string? Equipment, string ImageRef, string? ImageUrl, string? Instructions, int Sequence, int Sets, int RepetitionsMin, int RepetitionsMax, int RestSeconds, string? Notes, string TrackingMode, int? TargetDurationSeconds);
public sealed record WorkoutTemplateRequest(string Name, string? Notes, IReadOnlyList<WorkoutTemplateExerciseInput> Exercises);
public sealed record WorkoutTemplateResponse(Guid Id, string Name, string Notes, IReadOnlyList<WorkoutTemplateExerciseResponse> Exercises);
public sealed record ApplyWorkoutRequest(Guid StudentId);
public sealed record AppliedWorkoutResponse(Guid Id, Guid StudentId, string Name, int SuggestedOrder, int ExerciseCount);
public sealed record StudentTrainingHistoryResponse(IReadOnlyList<TrainingHistoryItem> Sessions);
public sealed record TrainingHistoryItem(Guid SessionId, string WorkoutName, string Status, DateTimeOffset StartedAt, DateTimeOffset? CompletedAt, int CompletedSets, IReadOnlyList<TrainingHistoryExerciseItem> Exercises);
public sealed record TrainingHistoryExerciseItem(string Name, int Sequence, string TrackingMode, bool ConfirmedWithoutDetails, IReadOnlyList<TrainingHistorySetItem> Sets);
public sealed record TrainingHistorySetItem(int SetNumber, decimal? WeightKg, int? Repetitions, int? DurationSeconds, DateTimeOffset CompletedAt);
public sealed record TrainerStudentWorkoutListResponse(IReadOnlyList<TrainerStudentWorkoutSummary> Workouts);
public sealed record TrainerStudentWorkoutSummary(Guid Id, string Name, string Notes, int SuggestedOrder, int ExerciseCount, DateTimeOffset CreatedAt);
public sealed record TrainerStudentWorkoutCreateRequest(string Name, string? Notes);
public sealed record TrainerStudentWorkoutDetail(Guid Id, Guid StudentId, string Name, string Notes, int SuggestedOrder, DateTimeOffset CreatedAt, IReadOnlyList<TrainerStudentWorkoutExercise> Exercises);
public sealed record ReorderTrainerStudentWorkoutsRequest(IReadOnlyList<Guid> WorkoutIds);
public sealed record TrainerStudentWorkoutExercise(Guid Id, Guid? ExerciseId, string Name, string? PrimaryMuscleGroup, string? Equipment, string? ImageRef, string? ImageUrl, string? Instructions, int Sequence, int Sets, int RepetitionsMin, int RepetitionsMax, int RestSeconds, string Notes, string TrackingMode, int? TargetDurationSeconds);
public sealed record TrainerStudentWorkoutUpdateRequest(string? Name, IReadOnlyList<TrainerStudentWorkoutExerciseInput> Exercises);
public sealed record TrainerStudentWorkoutExerciseInput(Guid? Id, Guid? ExerciseId, int Sequence, int Sets, int RepetitionsMin, int RepetitionsMax, int RestSeconds, string? Notes, string? TrackingMode = null, int? TargetDurationSeconds = null);
public sealed record TrainerExerciseCatalogItem(Guid Id, string Name, string Slug, string PrimaryMuscleGroup, string? Equipment, string ImageRef, string? ImageUrl, string? Instructions, bool IsActive, string DefaultTrackingMode, int? DefaultDurationSeconds);
